apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-svc-2-config
data:
  AWS_REGION: ap-southeast-2
  SQS_QUEUE_URL: https://sqs.ap-southeast-2.amazonaws.com/315073111691/sqs-process
  DB_HOST: database-1.c46o7dwnirhl.ap-southeast-2.rds.amazonaws.com
  DB_USER: admin
  DB_NAME: sqs
  DB_TABLE: userinfo
