apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  db-user: thanshi
  db-host: micro-svc-rds.ckc4evhlp36y.eu-north-1.rds.amazonaws.com
  db-name: userinfo
  db-table: UserInfoList 



