apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: 315073111691.dkr.ecr.ap-southeast-2.amazonaws.com/micro-svc-backend@sha256:0914588ffa1fe4b4551eb92b13f90987749a90b20bcf07c0ddb13f511ac43c75
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-user
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-name
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-table
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: db-password
