pipeline {
    agent any 
    stages {
        stage("build"){
            steps {
                script {
            sh """
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 315073111691.dkr.ecr.ap-southeast-2.amazonaws.com
            sudo docker build -t micro-svc-3 .
            sudo docker tag micro-svc-3:latest 315073111691.dkr.ecr.ap-southeast-2.amazonaws.com/micro-svc-3:latest
            sudo docker push 315073111691.dkr.ecr.ap-southeast-2.amazonaws.com/micro-svc-3:latest
            """
          }
        }
    }
  }
}